name: jxnblk
favicon: null
layout_spectrum: 0.25406
typography_spectrum: 0.23243
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6bf335'
    - '#5eccc2'
    - '#35f3e2'
    - '#f39735'
    - '#ffffff'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
