name: jxnblk
favicon: null
layout_spectrum: 0.23292
typography_spectrum: 0.22161
title: Jxnblk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00b9f2'
    - '#7cdcf9'
    - '#b5eafb'
    - '#0065a2'
    - '#008ec9'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
