name: jxnblk
favicon: null
layout_spectrum: 0.8
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c63ae'
    - '#8c97ab'
    - '#b4d1f1'
    - '#212f4a'
    - '#fcfdf8'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
