name: jxnblk
favicon: null
layout_spectrum: 0.99484
typography_spectrum: 0.2288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#405660'
    - '#cfd4d7'
    - '#6f8087'
    - '#909da3'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose:
  - name: stars
    item: null
    url: null
